### ISSUE TITLE
코드리뷰 제안

### ISSUE THREAD

**Issue by gimhanul** [jjarappappa/icecream#3]
[뱅크샐러드 코드리뷰 문화](https://blog.banksalad.com/tech/banksalad-code-review-culture/) 글을 읽었는데
PR code review할 때 P-) prefix로 우선순위 구분하면 좋을 것 같아서
우리도 하면 어떨까용

**Comment by leekyukin** [comment]
이런거 완전 좋죠

**Comment by gimhanul** [comment]
### Pn Rule
|prefix|description|type|
|---|---|---|
|P1|꼭 반영해주세요|Request changes|
|P2|적극적으로 고려해주세요|Request changes|
|P3|웬만하면 반영해 주세요|Comment|
|P4|반영해도 좋고 넘어가도 좋습니다|Approve|
|P5|그냥 사소한 의견입니다|Approve|
